### ISSUE TITLE
Remove Inputs

### ISSUE THREAD

**Issue by antimatter96** [shraddhaag/aoc#1]
Hi
I was going through your solutions and realised you have added the inputs by mistake
[About](https://adventofcode.com/2023/about#:~:text=Can%20I%20copy,it%20something%20similar.
)
Don't think we are allowed from this year (no mention [last year](https://web.archive.org/web/20221231041621/https://adventofcode.com/about) )

**Comment by ShraddhaAg** [comment]
Hey @antimatter96 thanks for letting me know! I have removed all inputs from the repository and also added a .gitignore to prevent further files from being committed!
